import {useEffect,useMemo,useState} from 'react'

const products=[
 {slug:'who',name:'WHO',subtitle:'Caller intelligence & communication',kind:'app',category:'Communication',tone:'who',summary:"Know who's calling.",desc:'Caller intelligence, a modern dialer, contacts and relay connectivity in one focused experience.',screens:['Dialer','Caller ID','Contacts','Relay'],features:['Caller intelligence','Modern dialer','Contacts & quick actions','Relay connectivity']},
 {slug:'squashai',name:'SquashAI',subtitle:'Your offline pocket AI',kind:'app',category:'Productivity',tone:'ai',summary:'Your AI. In your pocket.',desc:'A pocket AI experience built around local models, device-aware choices and a focused conversation interface.',screens:['Chat','Models','Offline','Settings'],features:['Offline models','Device-aware choices','Chat interface','One-model-at-a-time storage']},
 {slug:'medisquash',name:'MediSquash',subtitle:'Medical learning & clinical research',kind:'app',category:'Education',tone:'med',summary:'Study, search, research and learn.',desc:'Medical learning, patient workflows, research tools, notes and a modern search experience in one workspace.',screens:['Home','Search','Research','Notes'],features:['Medical search','Research workspace','Patient tools','Notes & library']},
 {slug:'netfliks',name:'Netfliks',subtitle:'Your personal streaming experience',kind:'app',category:'Entertainment',tone:'net',summary:'A Squashberry-built streaming experience.',desc:'A desktop/PWA streaming experience with a cinematic library, search and watch-focused interface.',screens:['Home','Details','Search','Player'],features:['Streaming library','Search','Installable desktop experience','Cinema browsing']},
 {slug:'netfinder',name:'Netfinder',subtitle:'Discover movies and series',kind:'app',category:'Entertainment',tone:'finder',summary:'Discover what to watch next.',desc:'A movie-discovery PWA focused on fast browsing, rich details and a polished installable web experience.',screens:['Discover','Details','Search','Watchlist'],features:['Movie discovery','Rich detail pages','Installable PWA','API adapter architecture']},
 {slug:'squashberrypay',name:'SquashberryPay',subtitle:'Payments and merchant tools',kind:'website',category:'Finance',tone:'pay',summary:'Payments for your products.',desc:'A web-first payment platform for checkout experiences, payment buttons and merchant tools.',screens:['Checkout','Merchant','Payments','Integrations'],features:['Payment buttons','Checkout flows','Merchant tools','Web integrations']}
]
const apps=products.filter(p=>p.kind==='app'),webs=products.filter(p=>p.kind==='website')

function Mark({tone}){return <svg className={'brand-svg mark-'+tone} viewBox="0 0 100 100" aria-hidden="true">
 {tone==='who'&&<><circle cx="50" cy="50" r="34" fill="none" stroke="currentColor" strokeWidth="9"/><path d="M31 38v25M69 38v25M31 50h38" stroke="currentColor" strokeWidth="9" strokeLinecap="round"/></>}
 {tone==='ai'&&<><path d="M50 13 58 42l29 8-29 8-8 29-8-29-29-8 29-8z" fill="currentColor"/><circle cx="76" cy="25" r="6" fill="currentColor"/></>}
 {tone==='med'&&<><rect x="40" y="17" width="20" height="66" rx="6" fill="currentColor"/><rect x="17" y="40" width="66" height="20" rx="6" fill="currentColor"/></>}
 {(tone==='net'||tone==='finder')&&<path d="M34 21 79 50 34 79z" fill="currentColor"/>}
 {tone==='pay'&&<><rect x="20" y="28" width="60" height="44" rx="10" fill="none" stroke="currentColor" strokeWidth="9"/><path d="M27 43h46" stroke="currentColor" strokeWidth="8"/><circle cx="35" cy="57" r="5" fill="currentColor"/></>}
 </svg>}

function Icon({p,large=false}){return <div className={'product-icon tone-'+p.tone+(large?' large':'')}><Mark tone={p.tone}/></div>}
function Get({p,install}){return <button className="get" onClick={e=>{e.stopPropagation();install(p)}}>{p.kind==='website'?'OPEN':'GET'}</button>}
function Row({p,open,install}){return <article className="row" onClick={()=>open(p.slug)}><Icon p={p}/><div className="row-copy"><b>{p.name}</b><span>{p.subtitle}</span><small>{p.category}</small></div><Get p={p} install={install}/><i>›</i></article>}

function Mock({p,label,i=0}){return <div className="mock"><div className="phone"><div className="island"/><div className="screen"><div className="status"><span>{i?'SquashApps':'9:41'}</span><span>● ●</span></div><div className="mock-brand"><Icon p={p}/><div><b>{label}</b><small>{p.subtitle}</small></div></div><div className="mock-card"><b>{p.summary}</b><small>{p.category} · Squashberry</small></div><div className="lines"><i/><i/><i/><i/></div><button>GET</button><div className="homebar"/></div></div></div>}

function Feature({p,kicker,title,body,open,light=false}){return <article className={'feature tone-'+p.tone+(light?' light':'')} onClick={()=>open(p.slug)}><div className="feature-art"><Mock p={p} label={p.screens[0]}/><div className="glow"/></div><div className="feature-copy"><small>{kicker}</small><h2>{title}</h2><p>{body}</p><b>View {p.name} <span>›</span></b></div></article>}

function Section({label,title,items,open,install,all}){return <section className="section"><header><div><small>{label}</small><h2>{title}</h2></div>{all&&<button onClick={all}>See All <span>›</span></button>}</header><div className="rows">{items.map(p=><Row key={p.slug} p={p} open={open} install={install}/>)}</div></section>}

function Rail({items,open}){return <div className="app-rail">{items.map(p=><button key={p.slug} onClick={()=>open(p.slug)}><Icon p={p} large/><b>{p.name}</b><span>{p.subtitle}</span></button>)}</div>}

function Today({open,install,setPage}){return <div className="page today">
 <div className="today-head"><div><small>FRIDAY, OCTOBER 2</small><h1>Today</h1></div></div>
 <section className="editorial">
  <Feature p={products[0]} kicker="APP OF THE DAY" title="Know who's calling." body="Caller intelligence, communication and a modern dialer in one experience." open={open}/>
  <Feature p={products[1]} kicker="MEET SQUASHAI" title="Your AI. In your pocket." body="A private pocket AI built around local models and a focused conversation experience." open={open}/>
 </section>
 <section className="collection-rail"><header><div><small>OUR FAVORITES</small><h2>Made by Squashberry</h2></div><button onClick={()=>setPage('apps')}>See All <span>›</span></button></header><Rail items={products.slice(0,5)} open={open}/></section>
 <Section label="NOW TRENDING" title="Apps in heavy rotation" items={apps.slice(0,3)} open={open} install={install} all={()=>setPage('apps')}/>
 <section className="editorial secondary-editorial"><Feature p={products[2]} kicker="GET STARTED" title="A smarter way to study medicine." body="Search, research, notes and patient workflows in one focused workspace." open={open}/></section>
 <Section label="NEW & NOTABLE" title="Fresh from Squashberry" items={[products[3],products[4],products[5]]} open={open} install={install}/>
 </div>}

function Collection({web,open,install}){let items=web?webs:apps;return <div className="page collection"><div className="collection-head"><small>{web?'SQUASHBERRY WEB':'SQUASHBERRY APPS'}</small><h1>{web?'Web':'Apps'}</h1><p>{web?'Web products and installable experiences made by Squashberry.':'Discover apps for communication, AI, learning and entertainment.'}</p></div><div className="chips">{(web?['All','Finance','Business']:['All','Communication','Productivity','Education','Entertainment']).map((x,i)=><button className={i?'':'selected'} key={x}>{x}</button>)}</div><section className="collection-feature"><div><small>{web?'NOW AVAILABLE':'FEATURED'}</small><h2>{web?'Payments, on the web.':'Tools for your everyday.'}</h2><p>{web?'SquashberryPay brings checkout and merchant tools to the web.':'A growing collection of focused products, designed and built by Squashberry.'}</p></div><Mock p={web?products[5]:products[0]} label={web?'Checkout':'WHO'}/></section><Section label={web?'WEB PRODUCTS':'ALL APPS'} title={web?'Explore the web':'Discover' } items={items} open={open} install={install}/></div>}

function Search({query,setQuery,open,install}){let r=useMemo(()=>{let q=query.trim().toLowerCase();return q?products.filter(p=>(p.name+' '+p.subtitle+' '+p.category+' '+p.desc).toLowerCase().includes(q)):products},[query]);return <div className="page search"><div className="search-head"><h1>{query?'Results':'Search'}</h1><label className="search-field"><span>⌕</span><input autoFocus value={query} placeholder="Search apps and web" onChange={e=>setQuery(e.target.value)}/></label></div>{r.length?<div className="rows">{r.map(p=><Row key={p.slug} p={p} open={open} install={install}/>)}</div>:<div className="empty"><b>No Results</b><span>Try another search.</span></div>}</div>}

function Product({p,back,install}){return <div className="page product"><button className="back" onClick={back}>‹ Back</button><div className="product-top"><Icon p={p} large/><div><small>{p.category}</small><h1>{p.name}</h1><p>{p.subtitle}</p><span>By Squashberry</span></div><Get p={p} install={install}/></div><div className="meta">{[['RATING','New','Be the first to review'],['AGE','4+','Years'],['CATEGORY',p.category,p.kind==='website'?'Web':'App'],['DEVELOPER','Squashberry','Squashberry']].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></div>)}</div><section className="shots"><h2>Preview</h2><div className="shot-track">{p.screens.map((s,i)=><Mock key={s} p={p} label={s} i={i}/>)}</div></section><section className="copy-grid"><div><small>ABOUT THIS {p.kind==='website'?'WEBSITE':'APP'}</small><h2>{p.summary}</h2><p>{p.desc}</p></div><div className="whats"><small>WHAT'S NEW</small><h3>Version 1.0</h3><p>Built and maintained by Squashberry.</p></div></section><section className="ratings"><div><h2>Ratings & Reviews</h2><div className="empty-card">No ratings yet</div></div><div><h2>Information</h2><dl><dt>Developer</dt><dd>Squashberry</dd><dt>Category</dt><dd>{p.category}</dd><dt>Availability</dt><dd>{p.kind==='website'?'Web':'Installable'}</dd></dl></div></section><section className="inside"><small>FEATURES</small><h2>Inside {p.name}</h2><div>{p.features.map((f,i)=><article key={f}><span>0{i+1}</span><b>{f}</b></article>)}</div></section></div>}

function Sheet({p,close,deferred}){return <div className="sheet-bg" onClick={close}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="grab"/><Icon p={p} large/><small>{p.kind==='website'?'WEBSITE':'APP'}</small><h2>{p.name}</h2><p>{p.kind==='website'?'Open the Squashberry web product.':'Install this Squashberry product when your browser supports PWA installation.'}</p><button onClick={async()=>{if(deferred){deferred.prompt();await deferred.userChoice}close()}}>{p.kind==='website'?'Done':'Install'}</button></div></div>}

function Header({page,setPage,query,setQuery}){return <header className="topbar"><div className="topbar-inner"><button className="brand" onClick={()=>setPage('today')}><span>S</span><b>SquashApps</b></button><nav>{[['today','Today'],['apps','Apps'],['web','Web']].map(([k,l])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}>{l}</button>)}</nav><div className="tools"><button className="desktop-search" onClick={()=>setPage('search')}>⌕ <span>Search</span></button><button className="avatar">S</button></div></div></header>}

function NavIcon({type}){let d=type==='today'?'M4 10.5 12 4l8 6.5v8.2a1.3 1.3 0 0 1-1.3 1.3H5.3A1.3 1.3 0 0 1 4 18.7z M9 20v-5h6v5':type==='apps'?'M5 5h5v5H5z M14 5h5v5h-5z M5 14h5v5H5z M14 14h5v5h-5z':type==='web'?'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M3.5 12h17 M12 3c2.3 2.5 3.4 5.5 3.4 9s-1.1 6.5-3.4 9c-2.3-2.5-3.4-5.5-3.4-9S9.7 5.5 12 3z':'M10.7 4a7 7 0 1 0 4.8 12.1l4.2 4.2 1.3-1.3-4.2-4.2A7 7 0 0 0 10.7 4zm0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10z';return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={d}/></svg>}
function Mobile({page,setPage}){return <nav className="mobile">{[['today','Today'],['apps','Apps'],['web','Web'],['search','Search']].map(([k,l])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}><NavIcon type={k}/><small>{l}</small></button>)}</nav>}

export default function App(){const[page,setPage]=useState('today'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[install,setInstall]=useState(null),[deferred,setDeferred]=useState(null);useEffect(()=>{let h=e=>{e.preventDefault();setDeferred(e)};addEventListener('beforeinstallprompt',h);return()=>removeEventListener('beforeinstallprompt',h)},[]);let open=s=>{setSelected(products.find(p=>p.slug===s));setPage('product');scrollTo(0,0)},doInstall=async p=>{if(p.kind==='app'&&deferred){deferred.prompt();await deferred.userChoice;setDeferred(null)}else setInstall(p)};let content=page==='product'&&selected?<Product p={selected} back={()=>setPage('today')} install={doInstall}/>:page==='apps'?<Collection open={open} install={doInstall}/>:page==='web'?<Collection web open={open} install={doInstall}/>:page==='search'?<Search query={query} setQuery={setQuery} open={open} install={doInstall}/>:<Today open={open} install={doInstall} setPage={setPage}/>;return <><Header page={page} setPage={setPage} query={query} setQuery={setQuery}/><main>{content}</main><footer><span><b>SquashApps</b> · Products by Squashberry</span><span>© 2026 Squashberry</span></footer><Mobile page={page} setPage={setPage}/>{install&&<Sheet p={install} deferred={deferred} close={()=>setInstall(null)}/>}</>}
