import {useEffect,useMemo,useState} from 'react'

const products=[
 {slug:'who',name:'WHO',subtitle:'Caller intelligence & communication',kind:'app',category:'Communication',tone:'who',summary:"Know who's calling.",desc:'Caller intelligence, a modern dialer, contacts and relay connectivity in one focused experience.',screens:['Caller ID','Dialer','Contacts','Relay'],features:['Caller intelligence','Modern dialer','Contacts & quick actions','Relay connectivity'],rating:null,reviews:0,age:'4+',size:'—',compatibility:'iPhone',languages:'English',what:'A focused caller-intelligence and communication experience.',searchTag:'Caller ID',version:'Beta 1.0',updated:'—',url:'https://squashberry.github.io/who/'},
 {slug:'squashai',name:'SquashAI',subtitle:'Your offline pocket AI',kind:'app',category:'Productivity',tone:'ai',summary:'Your AI. In your pocket.',desc:'A pocket AI experience built around local models, device-aware choices and a focused conversation interface.',screens:['Chat','Models','Offline','Settings'],features:['Offline models','Device-aware choices','Chat interface','One-model-at-a-time storage'],rating:null,reviews:0,age:'4+',size:'—',compatibility:'iPhone',languages:'English',what:'A private pocket AI built around local models and focused conversations.',searchTag:'AI',version:'—',updated:'—',url:'https://squashberry.github.io/squashai/'},
 {slug:'medisquash',name:'MediSquash',subtitle:'Medical learning & clinical research',kind:'app',category:'Education',tone:'med',summary:'Study, search, research and learn.',desc:'Medical learning, patient workflows, research tools, notes and a modern search experience in one workspace.',screens:['Search','Research','Notes','Patients'],features:['Medical search','Research workspace','Patient tools','Notes & library'],rating:null,reviews:0,age:'4+',size:'—',compatibility:'iPhone',languages:'English',what:'Medical learning and clinical research in one focused workspace.',searchTag:'Medical',version:'1.1.0',updated:'—'},
 {slug:'netfliks',name:'Netfliks',subtitle:'Your personal streaming experience',kind:'app',category:'Entertainment',tone:'net',summary:'A Squashberry-built streaming experience.',desc:'A desktop/PWA streaming experience with a cinematic library, search and watch-focused interface.',screens:['Home','Details','Search','Player'],features:['Streaming library','Search','Installable desktop experience','Cinema browsing'],rating:null,reviews:0,age:'4+',size:'Web',compatibility:'Web, desktop',languages:'English',what:'A cinematic streaming workspace for your personal library.',searchTag:'Streaming',version:'—',updated:'—'},
 {slug:'netfinder',name:'Netfinder',subtitle:'Discover movies and series',kind:'app',category:'Entertainment',tone:'finder',summary:'Discover what to watch next.',desc:'A movie-discovery PWA focused on fast browsing, rich details and a polished installable web experience.',screens:['Discover','Details','Search','Watchlist'],features:['Movie discovery','Rich detail pages','Installable PWA','API adapter architecture'],rating:null,reviews:0,age:'4+',size:'Web',compatibility:'Web, desktop',languages:'English',what:'A fast movie-discovery experience built for browsing and watchlists.',searchTag:'Movies',version:'—',updated:'—'},
 {slug:'squashberrypay',name:'SquashberryPay',subtitle:'Payments and merchant tools',kind:'website',category:'Finance',tone:'pay',summary:'Payments for your products.',desc:'A web-first payment platform for checkout experiences, payment buttons and merchant tools.',screens:['Checkout','Merchant','Payments','Integrations'],features:['Payment buttons','Checkout flows','Merchant tools','Web integrations'],rating:null,reviews:0,age:'—',size:'Web',compatibility:'Web',languages:'English',what:'A web-first payment surface for checkout and merchant workflows.',searchTag:'Payments',version:'2.0.0',updated:'—'}
]
const apps=products.filter(p=>p.kind==='app'),webs=products.filter(p=>p.kind==='website')

function Mark({tone}){return <svg className={'brand-svg mark-'+tone} viewBox="0 0 100 100" aria-hidden="true">
 {tone==='who'&&<><circle cx="50" cy="50" r="34" fill="none" stroke="currentColor" strokeWidth="9"/><path d="M31 38v25M69 38v25M31 50h38" stroke="currentColor" strokeWidth="9" strokeLinecap="round"/></>}
 {tone==='ai'&&<><path d="M50 12 59 41l29 9-29 9-9 29-9-29-29-9 29-9z" fill="currentColor"/><circle cx="77" cy="24" r="6" fill="currentColor"/></>}
 {tone==='med'&&<><rect x="39" y="15" width="22" height="70" rx="7" fill="currentColor"/><rect x="15" y="39" width="70" height="22" rx="7" fill="currentColor"/></>}
 {tone==='net'&&<path d="M31 17 84 50 31 83z" fill="currentColor"/>}
 {tone==='finder'&&<><circle cx="46" cy="45" r="23" fill="none" stroke="currentColor" strokeWidth="10"/><path d="m63 62 20 20" stroke="currentColor" strokeWidth="10" strokeLinecap="round"/></>}
 {tone==='pay'&&<><rect x="18" y="27" width="64" height="46" rx="11" fill="none" stroke="currentColor" strokeWidth="9"/><path d="M25 43h50M29 57h19" stroke="currentColor" strokeWidth="8" strokeLinecap="round"/><circle cx="69" cy="57" r="4" fill="currentColor"/></>}
 </svg>}

function Glyph({name,size=20,className=''}){const paths={search:'M11 4a7 7 0 1 0 4.95 11.95L20 20M11 6a5 5 0 1 0 0 10 5 5 0 0 0-10',share:'M12 16V4m0 0 4 4m-4-4L8 8M5 12v6a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-6',chevron:'m9 5 7 7-7 7',more:'M6 12h.01M12 12h.01M18 12h.01'};return <svg className={'glyph '+className} width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}
function Icon({p,large=false}){return <div className={'product-icon tone-'+p.tone+(large?' large':'')}><Mark tone={p.tone}/></div>}

function Get({p,install,installed,onOpen}){const isOpen=p.kind==='website'||installed;return <button className="get" onClick={e=>{e.stopPropagation();isOpen&&onOpen?onOpen(p):install(p,e.currentTarget)}}>{isOpen?'OPEN':'GET'}</button>}

function PreviewScreen({p,label,index=0}) {
 const screen=label||p.screens[index]||p.screens[0]
 if(p.tone==='who') return <div className="preview-app preview-who"><div className="preview-nav"><b>WHO</b><span>•••</span></div><div className="preview-caller"><small>INCOMING CALL</small><b>{index%2?'Unknown caller':'John Doe'}</b><span>{index%2?'+220 3XX XXX':'Mobile · Gambia'}</span></div><div className="preview-dial"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span></div><div className="preview-tab"><i>Recents</i><i>Contacts</i><i className="active">Dial</i></div><em>{screen}</em></div>
 if(p.tone==='ai') return <div className="preview-app preview-ai"><div className="preview-nav"><b>SquashAI</b><span>New</span></div><div className="ai-chip">OFFLINE · {index%2?'MEDIUM 1':'LITE'}</div><div className="ai-bubble me">Summarize this for me.</div><div className="ai-bubble bot">Absolutely. Here are the key ideas in a clearer format.</div><div className="ai-lines"><i/><i/><i/></div><div className="ai-input"><span>Ask SquashAI…</span><b>↑</b></div><em>{screen}</em></div>
 if(p.tone==='med') return <div className="preview-app preview-med"><div className="preview-nav"><b>MediSquash</b><span>⌕</span></div><div className="med-search">Search medicines, conditions, research…</div><div className="med-card"><small>CLINICAL RESEARCH</small><b>Joint pain: assessment and care</b><span>Evidence · 24 references</span></div><div className="med-row"><b>Patient workspace</b><span>›</span></div><div className="med-row"><b>Saved notes</b><span>›</span></div><em>{screen}</em></div>
 if(p.tone==='net') return <div className="preview-app preview-net"><div className="preview-nav"><b>Netfliks</b><span>⌕</span></div><div className="net-hero"><small>CONTINUE WATCHING</small><b>The last chapter</b><span>52 min remaining</span><button>Play</button></div><div className="poster-row"><i/><i/><i/><i/></div><div className="net-bottom">Home&nbsp;&nbsp; Search&nbsp;&nbsp; Library</div><em>{screen}</em></div>
 if(p.tone==='finder') return <div className="preview-app preview-finder"><div className="preview-nav"><b>Netfinder</b><span>⌕</span></div><div className="finder-title">Discover tonight</div><div className="finder-cards"><article><i/><b>Midnight Run</b><small>Movie · 2026</small></article><article><i/><b>Afterlight</b><small>Series · 2 seasons</small></article></div><div className="finder-list"><b>My Watchlist</b><span>8 saved ›</span></div><em>{screen}</em></div>
 return <div className="preview-app preview-pay"><div className="preview-nav"><b>SquashberryPay</b><span>•••</span></div><div className="pay-total"><small>AMOUNT DUE</small><b>GMD 1,250.00</b><span>Squashberry Store</span></div><div className="pay-method"><span>VISA •••• 2284</span><b>Change</b></div><button className="pay-button">Pay securely</button><em>{screen}</em></div>
}

function Mock({p,label,i=0,onOpen,compact=false}){return <button className={'mock preview-shell '+(compact?'preview-compact':'')} onClick={onOpen} aria-label={'Open '+(label||p.name)+' preview'}><div className="preview-device"><div className="preview-island"/><div className="preview-status"><span>9:41</span><span>● ●</span></div><PreviewScreen p={p} label={label} index={i}/><div className="preview-homebar"/></div></button>}

function Feature({p,kicker,title,body,open}){return <article className={'feature editorial-feature tone-'+p.tone} onClick={()=>open(p.slug)}><div className="feature-art"><Mock p={p} label={p.screens[0]} compact/></div><div className="feature-copy"><small>{kicker}</small><div className="editorial-meta"><span>{p.category}</span><span>Squashberry</span></div><h2>{title}</h2><p>{body}</p><b>View {p.name} <span>›</span></b></div></article>}

function Section({label,title,items,open,install,installed,onOpen,all}){return <section className="section"><header><div><small>{label}</small><h2>{title}</h2></div>{all&&<button onClick={all}>See All <span>›</span></button>}</header><div className="rows">{items.map(p=><Row key={p.slug} p={p} open={open} install={install} installed={installed[p.slug]} onOpen={onOpen}/>)}</div></section>

function Row({p,open,install,installed,onOpen}){return <article className="row" data-product={p.slug} onClick={()=>open(p.slug)}><Icon p={p}/><div className="row-copy"><b>{p.name}</b><span>{p.subtitle}</span><small>{p.category} · {p.searchTag}</small></div><Get p={p} install={install} installed={installed} onOpen={onOpen}/><i>›</i></article>

function Rail({items,open}){return <div className="app-rail">{items.map(p=><button key={p.slug} onClick={()=>open(p.slug)}><Icon p={p} large/><b>{p.name}</b><span>{p.subtitle}</span></button>)}</div>}

function Today({open,install,installed,onOpen,setPage}){const today=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();return <div className="page today">
 <div className="today-head"><div><small>{today}</small><h1>Today</h1></div></div>
 <section className="editorial">
  <Feature p={products[0]} kicker="SQUASHBERRY FEATURE" title="Know who's calling." body="Caller intelligence, communication and a modern dialer in one experience." open={open}/>
  <Feature p={products[1]} kicker="NEW FROM SQUASHBERRY" title="Your AI. In your pocket." body="A private pocket AI built around local models and a focused conversation experience." open={open}/>
 </section>
 <section className="collection-rail"><header><div><small>OUR FAVORITES</small><h2>Made by Squashberry</h2></div><button onClick={()=>setPage('apps')}>See All <span>›</span></button></header><Rail items={products.slice(0,5)} open={open}/></section>
 <Section label="POPULAR THIS WEEK" title="Apps in rotation" items={apps.slice(0,3)} open={open} install={install} installed={installed} onOpen={onOpen} all={()=>setPage('apps')}/>
 <section className="editorial secondary-editorial"><Feature p={products[2]} kicker="GET STARTED" title="A smarter way to study medicine." body="Search, research, notes and patient workflows in one focused workspace." open={open}/></section>
 <Section label="NEW & NOTABLE" title="Fresh from Squashberry" items={[products[3],products[4],products[5]]} open={open} install={install} installed={installed} onOpen={onOpen}/>
 </div>}

function Collection({web,open,install,installed,onOpen}){let items=web?webs:apps;return <div className="page collection"><div className="collection-head"><small>{web?'SQUASHBERRY WEB':'SQUASHBERRY APPS'}</small><h1>{web?'Web':'Apps'}</h1><p>{web?'Web products and installable experiences made by Squashberry.':'Discover apps for communication, AI, learning and entertainment.'}</p></div><div className="chips">{(web?['All','Finance','Business']:['All','Communication','Productivity','Education','Entertainment']).map((x,i)=><button className={i?'':'selected'} key={x}>{x}</button>)}</div><section className="collection-feature"><div><small>{web?'NOW AVAILABLE':'FEATURED'}</small><h2>{web?'Payments, on the web.':'Tools for your everyday.'}</h2><p>{web?'SquashberryPay brings checkout and merchant tools to the web.':'A growing collection of focused products, designed and built by Squashberry.'}</p></div><Mock p={web?products[5]:products[0]} label={web?'Checkout':'Caller ID'} compact/></section><Section label={web?'WEB PRODUCTS':'ALL APPS'} title={web?'Explore the web':'Discover'} items={items} open={open} install={install} installed={installed} onOpen={onOpen}/></div>}

function SearchResult({p,open,install,installed,onOpen}){return <article className="search-result" onClick={()=>open(p.slug)}><div className="search-result-top"><Icon p={p}/><div><b>{p.name}</b><span>{p.subtitle}</span><small>{p.category} · {p.searchTag}</small></div><Get p={p} install={install} installed={installed} onOpen={onOpen}/></div><div className="search-previews">{p.screens.slice(0,3).map((x,i)=><Mock key={x} p={p} label={x} i={i} compact onOpen={e=>e.stopPropagation()}/>)}</div></article>

function Search({query,setQuery,open,install,installed,onOpen}){const[scope,setScope]=useState('all');const base=scope==='apps'?apps:scope==='web'?webs:products;let r=useMemo(()=>{let q=query.trim().toLowerCase();return q?base.filter(p=>(p.name+' '+p.subtitle+' '+p.category+' '+p.desc+' '+p.features.join(' ')+' '+p.searchTag).toLowerCase().includes(q)):base},[query,scope]);return <div className="page search"><div className="search-head"><h1>{query?'Results':'Search'}</h1><label className="search-field"><Glyph name="search" size={19}/><input autoFocus value={query} placeholder="Search apps and web" onChange={e=>setQuery(e.target.value)}/>{query&&<button className="search-clear" onClick={()=>setQuery('')} aria-label="Clear search">×</button>}<kbd>⌘K</kbd></label><div className="search-scope" role="tablist" aria-label="Search scope">{[['all','All'],['apps','Apps'],['web','Web']].map(([k,l])=><button key={k} className={scope===k?'selected':''} onClick={()=>setScope(k)}>{l}</button>)}</div>{query&&<p className="search-count">{r.length} {r.length===1?'result':'results'}</p>}</div>{r.length?<div className="search-results">{r.map(p=><SearchResult key={p.slug} p={p} open={open} install={install} installed={installed[p.slug]} onOpen={onOpen}/>)}</div>:<div className="empty"><b>No Results</b><span>Try another search.</span><button onClick={()=>setQuery('')}>Clear Search</button></div>}</div>}

function Product({p,back,install,share,installed,onOpen}){const[viewer,setViewer]=useState(null);return <div className="page product">
 <div className="product-nav"><button className="product-back" onClick={back}><Glyph name="chevron" size={19}/>{p.kind==='website'?'Web':'Apps'}</button><button className="store-share nav-share" onClick={()=>share(p)} aria-label={'Share '+p.name}><Glyph name="share" size={18}/></button></div>
 <section className={'store-header store-header-'+p.tone}><div className="store-header-copy"><small>{p.kind==='website'?'WEB PRODUCT':'APP'} · {p.category.toUpperCase()}</small><h2>{p.summary}</h2><p>{p.what}</p></div><div className="store-header-preview"><Mock p={p} label={p.screens[0]} compact/></div></section>
 <section className="store-identity"><Icon p={p} large/><div className="store-title"><h1>{p.name}</h1><p>{p.subtitle}</p><a href="#developer">Squashberry</a></div><div className="store-action"><Get p={p} install={install} installed={installed} onOpen={onOpen}/></div></section>
 <div className="store-meta"><div><b>{p.rating??'—'}</b><span>{p.rating?`${p.reviews} Ratings`:'Ratings'}</span></div><div><b>{p.age}</b><span>Age</span></div><div><b>{p.category}</b><span>Category</span></div><div><b>{p.compatibility}</b><span>Compatibility</span></div></div>
 <section className="store-section store-preview"><header><h2>Preview</h2><span>Swipe to explore</span></header><div className="store-shots">{p.screens.map((x,i)=><Mock key={x} p={p} label={x} i={i} onOpen={()=>setViewer(i)}/>)}</div></section>
 <section className="store-section store-about"><header><h2>About This {p.kind==='website'?'Website':'App'}</h2></header><div><p className="store-description">{p.desc}</p><button className="more">More</button></div></section>
 <section className="store-section store-whats"><header><h2>What's New</h2></header><div><b>Version {p.version||'—'}</b><p>{p.what}</p></div></section>
 <section className="store-section store-ratings"><header><h2>Ratings & Reviews</h2></header><div className="rating-layout"><div className="rating-score"><strong>{p.rating??'—'}</strong><div className="stars">{[1,2,3,4,5].map(x=><span key={x}>☆</span>)}</div><span>{p.rating?p.reviews+" Ratings":"No Ratings Yet"}</span></div><div className="rating-bars">{[5,4,3,2,1].map(x=><div key={x}><b>{x}</b><i><span style={{width:p.rating?'72%':'0%'}}/></i></div>)}</div></div></section>
 <section className="store-section store-privacy"><header><h2>App Privacy</h2></header><div className="privacy-card"><div><b>Privacy details</b><span>Review how this product handles data in the Privacy Policy.</span></div><a href="#privacy">See Details <Glyph name="chevron" size={15}/></a></div></section><section className="store-section store-info"><header><h2>Information</h2></header><dl><div><dt>Provider</dt><dd>Squashberry</dd></div><div><dt>Category</dt><dd>{p.category}</dd></div><div><dt>Version</dt><dd>{p.version||'—'}</dd></div><div><dt>Updated</dt><dd>{p.updated||'—'}</dd></div><div><dt>Compatibility</dt><dd>{p.compatibility}</dd></div><div><dt>Languages</dt><dd>{p.languages}</dd></div><div><dt>Age Rating</dt><dd>{p.age}</dd></div></dl></section>
 <section className="store-section store-features"><header><h2>Features</h2></header><div>{p.features.map((f,i)=><article key={f}><span>0{i+1}</span><div><b>{f}</b><small>{p.screens[i]||p.category}</small></div><i>›</i></article>)}</div></section>
 <section className="store-links" id="developer"><a href="#developer">Developer Website <span>›</span></a><a href="#support">App Support <span>›</span></a><a href="#privacy">Privacy Policy <span>›</span></a></section>
 {viewer!==null&&<div className="preview-lightbox" onClick={()=>setViewer(null)}><button className="lightbox-close" onClick={()=>setViewer(null)} aria-label="Close">×</button><button className="lightbox-arrow left" onClick={e=>{e.stopPropagation();setViewer((viewer-1+p.screens.length)%p.screens.length)}}>‹</button><div className="lightbox-stage" onClick={e=>e.stopPropagation()}><Mock p={p} label={p.screens[viewer]} i={viewer}/><b>{p.screens[viewer]}</b></div><button className="lightbox-arrow right" onClick={e=>{e.stopPropagation();setViewer((viewer+1)%p.screens.length)}}>›</button></div>}
 </div>}

function Sheet({p,close,deferred,origin}){const style=origin?{'--sheet-origin-x':origin.x+'px','--sheet-origin-y':origin.y+'px'}:{};return <div className="sheet-bg" onClick={close}><div className="sheet" style={style} onClick={e=>e.stopPropagation()}><div className="grab"/><Icon p={p} large/><small>{p.kind==='website'?'WEB PRODUCT':'APP'}</small><h2>{p.name}</h2><p>{p.kind==='website'?'Open the Squashberry web product.':'Install this Squashberry product when your browser supports PWA installation.'}</p><button onClick={async()=>{if(deferred){deferred.prompt();await deferred.userChoice;close()}else close()}}>{p.kind==='website'?'Done':'Install'}</button></div></div>}

function Header({page,setPage,theme,toggleTheme}){return <header className={'topbar '+(page==='product'?'product-mode':'')}><div className="topbar-inner"><button className="brand" onClick={()=>setPage('today')}><span>S</span><b>SquashApps</b></button><nav>{[['today','Today'],['apps','Apps'],['web','Web']].map(([k,l])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}>{l}</button>)}</nav><div className="tools"><button className="desktop-search" onClick={()=>setPage('search')}><Glyph name="search" size={16}/><span>Search</span></button><button className="avatar" onClick={toggleTheme} aria-label="Toggle appearance">S</button></div></div></header>}

function NavIcon({type}){let d=type==='today'?'M4 10.5 12 4l8 6.5v8.2a1.3 1.3 0 0 1-1.3 1.3H5.3A1.3 1.3 0 0 1 4 18.7z M9 20v-5h6v5':type==='apps'?'M5 5h5v5H5z M14 5h5v5h-5z M5 14h5v5H5z M14 14h5v5h-5z':type==='web'?'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M3.5 12h17 M12 3c2.3 2.5 3.4 5.5 3.4 9s-1.1 6.5-3.4 9c-2.3-2.5-3.4-5.5-3.4-9S9.7 5.5 12 3z':'M10.7 4a7 7 0 1 0 4.8 12.1l4.2 4.2 1.3-1.3-4.2-4.2A7 7 0 0 0 10.7 4zm0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10z';return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={d}/></svg>}

function Mobile({page,setPage,hidden}){return <nav className={'mobile '+(hidden?'mobile-hidden':'')}>{[['today','Today'],['apps','Apps'],['web','Web'],['search','Search']].map(([k,l])=><button className={page===k?'active':''} key={k} onClick={()=>setPage(k)}><NavIcon type={k}/><small>{l}</small></button>)}</nav>}

const BASE='/SquashApps'
function productPath(p){return '/'+(p.kind==='website'?'web':'apps')+'/'+p.slug}
function pagePath(page){return page==='today'?'/':'/'+page}
function readRoute(){let raw=location.pathname;const redirected=new URLSearchParams(location.search).get('__route');if(redirected){raw=redirected.split('?')[0]||'/';history.replaceState({},'',BASE+(raw.startsWith('/')?raw:'/'+raw))}raw=raw.replace(BASE,'')||'/';if(raw==='/'||raw==='/today')return {page:'today'};if(raw==='/apps'||raw==='/web'||raw==='/search')return {page:raw.slice(1)};const match=raw.match(/^\/(apps|web)\/([^/]+)$/);if(match){const p=products.find(x=>x.slug===match[2]&&(match[1]==='web'?x.kind==='website':x.kind==='app'));if(p)return {page:'product',selected:p,fromPage:match[1]}}return {page:'today'}}
function runViewTransition(fn){if(typeof document.startViewTransition==='function')return document.startViewTransition(fn);fn()}

export default function App(){
 const initial=readRoute();
 const[page,setPage]=useState(initial.page),[query,setQuery]=useState(''),[selected,setSelected]=useState(initial.selected||null),[install,setInstall]=useState(null),[deferred,setDeferred]=useState(null),[installOrigin,setInstallOrigin]=useState(null),[fromPage,setFromPage]=useState(initial.fromPage||'today'),[direction,setDirection]=useState('forward'),[tabHidden,setTabHidden]=useState(false),[theme,setTheme]=useState(()=>localStorage.getItem('squashapps-theme')||'system'),[installed,setInstalled]=useState(()=>{try{return JSON.parse(localStorage.getItem('squashapps-installed')||'{}')}catch{return {}}});
 useEffect(()=>{let h=e=>{e.preventDefault();setDeferred(e)};addEventListener('beforeinstallprompt',h);return()=>removeEventListener('beforeinstallprompt',h)},[]);
 useEffect(()=>{const root=document.documentElement;const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);root.dataset.theme=dark?'dark':'light';localStorage.setItem('squashapps-theme',theme)},[theme]);
 useEffect(()=>{localStorage.setItem('squashapps-installed',JSON.stringify(installed))},[installed]);
 useEffect(()=>{const onKey=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();navigate('search')}};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[page]);
 useEffect(()=>{let last=scrollY;const onScroll=()=>{const next=scrollY;setTabHidden(next>last&&next>80);if(Math.abs(next-last)>3)last=next};addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);
 useEffect(()=>{const onPop=()=>{const r=readRoute();setPage(r.page);setSelected(r.selected||null);setFromPage(r.fromPage||'today');setTabHidden(false);scrollTo(0,0)};addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop)},[]);
 useEffect(()=>{document.title=page==='product'&&selected?selected.name+' — SquashApps':page==='today'?'SquashApps — Today':page==='search'?'Search — SquashApps':page==='web'?'Web — SquashApps':'Apps — SquashApps'},[page,selected]);
 const navigate=(next,options={})=>{const replace=!!options.replace;const nextPath=pagePath(next);const dir=(page==='search'&&next!=='search')?'back':'forward';runViewTransition(()=>{setDirection(dir);history[replace?'replaceState':'pushState']({},'',BASE+nextPath);setPage(next);setSelected(null);setFromPage(next);setTabHidden(false);scrollTo({top:0,behavior:'auto'})})};
 const open=s=>{const p=products.find(x=>x.slug===s);if(!p)return;document.body.dataset.transitionProduct=p.slug;setTimeout(()=>{delete document.body.dataset.transitionProduct},700);runViewTransition(()=>{setFromPage(page==='product'?'today':page);setSelected(p);setDirection('forward');history.pushState({},'',BASE+productPath(p));setPage('product');setTabHidden(false);scrollTo(0,0)})};
 const backProduct=()=>{const target=fromPage==='web'||fromPage==='apps'?fromPage:'today';if(selected)document.body.dataset.transitionProduct=selected.slug;setTimeout(()=>{delete document.body.dataset.transitionProduct},700);runViewTransition(()=>{history.pushState({},'',BASE+pagePath(target));setDirection('back');setSelected(null);setPage(target);setTabHidden(false);scrollTo(0,0)})};
 const share=async p=>{const data={title:p.name,text:p.subtitle,url:location.href};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard)await navigator.clipboard.writeText(location.href)}catch{}};
 const doOpen=p=>{if(p.url)window.open(p.url,'_blank','noopener,noreferrer');else setInstall(p)};
 const doInstall=async(p,origin)=>{setInstallOrigin(origin?(()=>{const r=origin.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})():null);if(p.kind==='app'&&deferred){deferred.prompt();const result=await deferred.userChoice;if(result?.outcome==='accepted')setInstalled(s=>({...s,[p.slug]:true}));setDeferred(null)}else setInstall(p)};
 const toggleTheme=()=>setTheme(t=>t==='dark'?'light':t==='light'?'system':'dark');
 let content=page==='product'&&selected?<Product p={selected} back={backProduct} install={doInstall} share={share} installed={!!installed[selected.slug]} onOpen={doOpen}/>:page==='apps'?<Collection open={open} install={doInstall} installed={installed} onOpen={doOpen}/>:page==='web'?<Collection web open={open} install={doInstall} installed={installed} onOpen={doOpen}/>:page==='search'?<Search query={query} setQuery={setQuery} open={open} install={doInstall} installed={installed} onOpen={doOpen}/>:<Today open={open} install={doInstall} installed={installed} onOpen={doOpen} setPage={navigate}/>;
 return <><Header page={page} setPage={navigate} theme={theme==='dark'?'dark':document.documentElement.dataset.theme||'light'} toggleTheme={toggleTheme}/><main key={page} className={'route route-'+page+' direction-'+direction}>{content}</main><footer><span><b>SquashApps</b> · Products by Squashberry</span><span>© {new Date().getFullYear()} Squashberry</span></footer><Mobile page={page} setPage={navigate} hidden={tabHidden}/>{install&&<Sheet p={install} deferred={deferred} origin={installOrigin} close={()=>{setInstall(null);setInstallOrigin(null)}}/>}</>
}